#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 25 19:25:21 2019

@author: david
"""

import rasterio as rio
import matplotlib.pyplot as plt
import skimage 
from skimage.color import rgb2gray
from skimage.filters import sobel
from skimage.segmentation import felzenszwalb, slic, quickshift, watershed
from skimage.segmentation import mark_boundaries
from skimage.util import img_as_float

tif = rio.open('data/swindon/masked.tif')

img = img_as_float(tif)

segments_fz = felzenszwalb(img, scale=100, sigma=0.5, min_size=0.5)


